title: Kempner Institute HPC Handbook
copyright: " 2024, Kempner Institute"
author: Kempner Institute
logo: figures/png/logo_place_holder.png
execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex


bibtex_bibfiles:
  - references.bib

