title: Kempner Institute HPC Handbook
copyright: " 2024, The President and Fellows of Harvard College"
author: Kempner Institute
logo: figures/svg/Kempner-logo_Full-Color-Full-Name-Harvard.svg
execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/KempnerInstitute/kempner-hpc-handbook
  path: kempner_hpc_handbook
  branch: main

html:
  use_issues_button: true
  use_repository_button: true