title: Kempner Institute HPC Handbook
copyright: " 2024, Kempner Institute"
author: Kempner Institute
logo: figures/svg/Kempner-logo_Full-Color-Full-Name-Harvard.svg
execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

