name: Check for build (Ubuntu)


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter-book
    - name: Build
      run: |
        set -o pipefail
        jupyter-book build kempner_computing_handbook 2>&1 | tee build.log
        if grep -q "WARNING: " build.log; then
        echo "::error ::Build produced warnings"
        exit 1
        fi
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: book
        path: kempner_computing_handbook/_build/html
