name: deploy_computing_handbook

on:
  push:
    branches:
    - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Build the book
      run: |
        rm -rf kempner_computing_handbook/_build
        uv run jupyter-book build kempner_computing_handbook

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: kempner_computing_handbook/_build/html
        cname: handbook.eng.kempnerinstitute.harvard.edu
