name: Build and Push Docker Image

on:
  push:
    paths:
      - 'Docker/Dockerfile'
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract version from Dockerfile
      id: docker_version
      run: echo "::set-output name=VERSION::$(grep 'ENV VERSION=' Docker/Dockerfile | cut -d '=' -f2)"

    - name: Get short SHA
      id: short_sha
      run: echo "::set-output name=SHORT_SHA::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Get commit date
      id: commit_date
      run: echo "::set-output name=COMMIT_DATE::$(git show -s --format=%cd --date=format:%y%m%d ${GITHUB_SHA})"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Docker/Dockerfile
        push: true
        tags: kempnerinstitute/hpc_handbook_jb:${{ steps.docker_version.outputs.VERSION }}-${{ steps.commit_date.outputs.COMMIT_DATE }}-${{ steps.short_sha.outputs.SHORT_SHA }}
