name: spellcheck

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Install uv
      uses: astral-sh/setup-uv@v8.1.0
      with:
        enable-cache: true

    - name: Run codespell
      run: |
        uvx codespell \
          --ignore-words=.codespell-ignore \
          --skip="_build,.venv,uv.lock,*.bib,LICENSE,.git,node_modules,_static,*.ai,*.pdf,*.eps,*.ps,*.svg,*.ipynb_checkpoints,package-lock.json" \
          kempner_computing_handbook README.md CONTRIBUTING.md
